name: Deploy via git-ftp
on: push
jobs:
  deploy:
    environment: Infinity
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: git-ftp push
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://ftpupload.net/htdocs/"
        user: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}
        options: --verbose --debug
